# Change these first
owner: pluto # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Notary WS
    url: wss://notary.pluto.xyz
  - name: Notary HTTP
    url: https://notary.pluto.xyz
  - name: Frame
    url: https://frame.pluto.xyz/
  - name: Playground
    url: https://playground.pluto.xyz/
  - name: Browser Inspector
    url: https://browser-inspector.pluto.xyz/

assignees:
  - eerieeight

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pluto.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pluto Status
  introTitle: '**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub.'
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/pluto/status

notifications:
  - type: slack
    channel: '#devops'
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
