# Change these first
owner: pluto # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Notary WS
    url: notary.pluto.xyz
    port: 443
    check: 'tcp-ping'
  - name: Notary HTTP
    url: https://notary.pluto.xyz
  - name: Frame
    url: https://frame.pluto.xyz/
  - name: Playground
    url: https://playground.pluto.xyz/
  - name: Browser Inspector
    url: https://browser-inspector.pluto.xyz/inspector.html

assignees:
  - eerieeight

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pluto.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/20591802?s=200&v=4
  name: Pluto Status
  introTitle: 'Pluto Services Status'
  introMessage: 'This page provides real-time status updates for our services. If you are experiencing an issue not listed here, please contact support.'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: slack
    channel: '#devops'
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
